[[constraint]]
  branch = "master"
  name = "github.com/containership/csctl"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.8.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[prune]
  go-tests = true
  unused-packages = true
